classDiagram

namespace PkgSanction {
  class SanctionAbsence
  class ReglesDeSanction
  class Notification
  class SanctionAbsencePrevisionnelle
}

class SanctionAbsencePrevisionnelle{
  + id: int
}

class SanctionAbsence{
  + id: int
  + dateDebut: date
  + dateFin: date
}

class ReglesDeSanction{
  + id: int
  + titre: string
  + description: string
  + absencesMax: int
  + penalite: string
  + seuilDeNotification: int
  + duree: int
  + note: string
}

class Notification {
   + id: int
   + message: string
}

namespace PkgUtilisateurs {
class Apprenant
}

namespace PkgAbsence {
  class Absence
  class Seance
  class JustificationAbsence
}
 
namespace PkgEmploiTemps {
  class DureeSeance
}

Absence -- Apprenant
Seance "1" -- "*" Absence
Seance  --> "1" DureeSeance

Absence "0..1" --> "0..1" JustificationAbsence : "peut avoir"

ReglesDeSanction "1" --> "0..*" SanctionAbsencePrevisionnelle : "s'applique à"
ReglesDeSanction "1" --> "0..*" SanctionAbsence : "s'applique à"
SanctionAbsence "1" --> "1..*" Notification : "déclenche"
SanctionAbsence "1" --> "1..*" Absence : "basée sur"
SanctionAbsencePrevisionnelle "1" --> "1..*" Absence : "analyse"
Apprenant "1" --> "0..*" Notification : "reçoit"

