classDiagram
class ReglesDeSanction {
    -id: int
    -titre: string
    -description: string
    -absencesMax: int
    -penalite: string
    -seuilDeNotification: int
    -duree: int
    -Note: string
}

class Apprenant {
    -id: int
    -prenom: string
    -nom: string
    -group: string
    -email: string
    -password: string
    +consulterNotificationSanction()
    +consulterHistoriqueSanctions()
}

class Sanction {
    -id: int
    -dateDebut: date
    -statut: string
    +appliquerSanction()
    +obtenirDetailsSanction()
}

class Absence {
    -id: int
    -date: date
    -justifiee: boolean
}

class Justification {
    -id: int
    -document: string
    -dateSoumission: date
    -approuvee: boolean
}

class Notification {
    -id: int
    -message: string
    -horodatage: date
    +envoyerNotification()
}

class ResponsableDesApprenants {
    -id: int
    -prenom: string
    -nom: string
    -email: string
    -password: string
    +definirReglesDeSanction()
    +surveillerSanctions()
    +consulterHistoriqueSanctions()
    +rechercherSanctionsParApprenant()
    +filtrerSanctionsParPenalite()
}

ResponsableDesApprenants "1" --> "0..*" Notification : "reçoit"
ResponsableDesApprenants "1" --> "0..*" ReglesDeSanction : "définit"
ReglesDeSanction "1" --> "0..*" Sanction : "s'applique à"
Sanction "1..*" --> "1..*" Notification : "déclenche"
Absence "1..*" --> "1" Apprenant : "appartient à"
Apprenant "0..*" --> "0..*" Notification : "reçoit"
Justification "1" --> "0..*" Absence : "justifie"
Sanction "1" --> "1" Apprenant : "s'applique à"