@startuml
left to right direction
actor "Responsable des Apprenants" as Admin

rectangle Gérer-les-Sanctions-(sprint-1) {
  usecase "Consulter les Statistiques" as UC8
  usecase "Sanctions récentes" as UC8_1
  usecase "Total des sanctions" as UC8_2
  usecase "Sanctions non résolues" as UC8_3
  usecase "Évolution mensuelle des sanctions" as UC8_4
  usecase "Répartition par type de sanction" as UC8_5
}


Admin -- UC8

UC8 <.. UC8_1 : <<extend>>
UC8 <.. UC8_2 : <<extend>>
UC8 <.. UC8_3 : <<extend>>
UC8 <.. UC8_4 : <<extend>>
UC8 <.. UC8_5 : <<extend>>

@enduml
