@startuml
left to right direction
actor "Responsable des Apprenants" as Admin
actor Apprenant

rectangle Gérer-les-Sanctions {
  usecase "Définir les Règles de Sanction" as UC1
  usecase "Surveiller et Appliquer les Sanctions" as UC2
  usecase "Notifier d'une Sanction" as UC3
  usecase "Consulter l'Historique des Sanctions" as UC4
  usecase "Gestion des Sanctions" as UC5
  usecase "Rechercher des Sanctions par Apprenant" as UC6
  usecase "Filtrer les Sanctions par Penalite" as UC7
  usecase "Consulter les Statistiques" as UC8
}

note right of UC2
"Le système vérifie automatiquement chaque jour si un apprenant
a dépassé la limite autorisée d'absences sans justification 
et applique les sanctions appropriées.
Le rôle 'Responsable des Apprenants' peut déclencher 
manuellement cette vérification à tout moment."
end note

Admin -- UC1

Admin -- UC3
Admin -- UC5
Admin -- UC8

Apprenant -- UC3
Apprenant -- UC4
UC5 <.. UC4 : <<extend>>
UC5 ..> UC2 : <<include>>
UC5 ..> UC6 : <<include>>
UC5 ..> UC7 : <<include>>
