@startuml
left to right direction
actor "Responsable des Apprenants" as Admin
actor Apprenant

rectangle Gérer-les-Sanctions-(sprint-3) {
  usecase "Notifier d'une Sanction" as UC3
  usecase "Gestion des Sanctions" as UC5
  usecase "Rechercher des Sanctions par Apprenant" as UC6
  usecase "Filtrer les Sanctions par Penalite" as UC7
}


Admin -- UC3
Admin -- UC5

Apprenant -- UC3
UC5 ..> UC6 : <<include>>
UC5 ..> UC7 : <<include>>
