@startuml
left to right direction
actor "Responsible for Learners" as Admin

rectangle Gérer-les-Sanctions-(sprint-2) {
  usecase "Définir les Règles de Sanction" as UC1
  usecase "Suivi des sanctions" as UC2
  usecase "Gestion des Sanctions" as UC5
}

' note right of UC2
' "Le système vérifie automatiquement chaque jour si un apprenant
' a dépassé la limite autorisée d'absences sans justification 
' et applique les sanctions appropriées.
' Le rôle 'Responsable des Apprenants' peut déclencher 
' manuellement cette vérification à tout moment."
' end note

Admin -- UC5
Admin -- UC1

UC5 ..> UC2 : <<include>>

@enduml
