@startuml
left to right direction
actor "Responsible for Learners" as Admin
actor Learner

rectangle Manage-Sanctions {
  usecase "Define Sanction Rules" as UC1
  usecase "Apply Sanctions" as UC2
  usecase "Notify of Sanction" as UC3
  usecase "View Sanction History" as UC4
  usecase "Dashboard for Managing Sanctions" as UC5
  usecase "Search and Filter Sanctions" as UC6
}

Admin -- UC1
Admin -- UC2
Admin -- UC3
Admin -- UC5
Admin -- UC6
Learner -- UC3
Learner -- UC4
@enduml
